
version: '3'
services:
  database:
    container_name: database
    image: mariadb:10.2.7
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/script/init.sql
    command: "--init-file /script/init.sql"
    networks:
      - directus
    environment:
      MYSQL_ROOT_PASSWORD: 'directus'
      MYSQL_USER: 'directus'
      MYSQL_PASSWORD: 'directus'
      MYSQL_DATABASE: 'directus'

#  cache:
#    container_name: cache
#    image: redis:6
#    networks:
#      - directus

#https://docs.directus.io/getting-started/installation/docker/
  directus:
    container_name: directus
    image: directus/directus:9.6.0
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
#      - cache
      - database
    restart: unless-stopped  
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

#      CACHE_ENABLED: 'true'
#      CACHE_STORE: 'redis'
#      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'
      
  terminal:
    container_name: terminal
    image: mypacr/terminal
    ports: 
      - 3000:3000
    networks:
      - directus
    depends_on:
      - directus
    restart: unless-stopped  
    environment:
      DIRECTUS_API_URL: directus:8055
      DIRECTUS_API_TOKEN: 1234
      
  portalapi:
    container_name: portalapi
    image: mypacr/portalapi
    ports: 
      - 80:80
    networks:
      - directus
    depends_on:
      - terminal
    restart: unless-stopped  

  portalfront:
    container_name: portalfront
    image: mypacr/portalfront
    ports: 
      - 2000:2000
    networks:
      - directus
    depends_on:
      - portalapi
    restart: unless-stopped  
    environment: 
      API_URL: portalapi:80/api
      API_PORTALFRONT: portalfront:2000
      SMARTSCHOOL_URL:
      SMARTSCHOOL_CLIENTID:
      

networks:
  directus:
