const altCodeArry = []

const service = {}

altCodeArry['48'] = '0'
altCodeArry['49'] = '1'
altCodeArry['50'] = '2'
altCodeArry['51'] = '3'
altCodeArry['52'] = '4'
altCodeArry['53'] = '5'
altCodeArry['54'] = '6'
altCodeArry['55'] = '7'
altCodeArry['56'] = '8'
altCodeArry['57'] = '9'
altCodeArry['58'] = ':'
altCodeArry['59'] = ';'
altCodeArry['60'] = '<'
altCodeArry['61'] = '='
altCodeArry['62'] = '>'
altCodeArry['63'] = '?'
altCodeArry['65'] = 'A'
altCodeArry['66'] = 'B'
altCodeArry['67'] = 'C'
altCodeArry['68'] = 'D'
altCodeArry['69'] = 'E'
altCodeArry['70'] = 'F'
altCodeArry['71'] = 'G'
altCodeArry['72'] = 'H'
altCodeArry['73'] = 'I'
altCodeArry['74'] = 'J'
altCodeArry['75'] = 'K'
altCodeArry['76'] = 'L'
altCodeArry['77'] = 'M'
altCodeArry['78'] = 'N'
altCodeArry['93'] = ']'
altCodeArry['94'] = '^'
altCodeArry['95'] = '_'
altCodeArry['96'] = '`'
altCodeArry['97'] = 'a'
altCodeArry['98'] = 'b'
altCodeArry['99'] = 'c'
altCodeArry['100'] = 'd'
altCodeArry['101'] = 'e'
altCodeArry['102'] = 'f'
altCodeArry['103'] = 'g'
altCodeArry['104'] = 'h'
altCodeArry['105'] = 'i'
altCodeArry['106'] = 'j'
altCodeArry['107'] = 'k'
altCodeArry['108'] = 'l'
altCodeArry['109'] = 'm'
altCodeArry['110'] = 'n'
altCodeArry['111'] = 'o'
altCodeArry['112'] = 'p'
altCodeArry['113'] = 'q'
altCodeArry['114'] = 'r'
altCodeArry['115'] = 's'
altCodeArry['116'] = 't'
altCodeArry['117'] = 'u'
altCodeArry['118'] = 'v'
altCodeArry['119'] = 'w'
altCodeArry['120'] = 'x'
altCodeArry['121'] = 'y'
altCodeArry['122'] = 'z'
altCodeArry['123'] = '{'
altCodeArry['124'] = '|'
altCodeArry['125'] = '}'
altCodeArry['126'] = '~'

service.convertAltCode = (code) => {
  return altCodeArry[code] ? altCodeArry[code] : ''
}

export default service
